(()=>{"use strict";
const KEY="workoutJournal.v2";const OLD="workoutJournal.v1";const DAYS=["Понедельник","Вторник","Среда","Четверг","Пятница","Суббота","Воскресенье"];
const seed=["Приседания с гирей","Махи гирей","Жим гири","Тяга гири в наклоне","Трастер с гирей","Отжимания","Разведение с эспандером","Face pull"].map(name=>({id:uid("ex"),name,description:"",defaultLoad:""}));
function uid(p="id"){return p+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function load(){try{let r=localStorage.getItem(KEY);if(r)return normalize(JSON.parse(r));let old=localStorage.getItem(OLD);if(old){let x=JSON.parse(old);let n={exercises:(x.exercises||[]).map(e=>({...e,defaultLoad:e.defaultLoad||e.load||""})),workouts:(x.workouts||[]).map(w=>({...w,exerciseIds:w.exerciseIds||[]})),completions:[] ,presets:[]};localStorage.setItem(KEY,JSON.stringify(n));return normalize(n)}}catch(e){}return {exercises:seed,workouts:[],completions:[],presets:[]}}
function normalize(s){s.exercises=s.exercises||seed;s.workouts=s.workouts||[];s.completions=s.completions||s.history||[];s.presets=s.presets||[];s.workouts.forEach(w=>{w.exerciseIds=w.exerciseIds||[];w.items=w.items||w.exerciseIds.map(id=>({exerciseId:id,reps:"",load:""}))});return s}
let state=load(),weekOffset=0,sound=true,audio=null,timerMode="stopwatch",stage="warmup",timer=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function toast(s){const e=$("toast");e.textContent=s;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1700)}
function monday(d){let x=new Date(d);x.setHours(0,0,0,0);let n=x.getDay();x.setDate(x.getDate()-(n===0?6:n-1));return x}function dayIndex(d){let n=new Date(d).getDay();return n===0?6:n-1}function dates(){let x=monday(new Date);x.setDate(x.getDate()+weekOffset*7);return Array.from({length:7},(_,i)=>{let d=new Date(x);d.setDate(d.getDate()+i);return d})}function fmt(d){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)}function dateKey(d){return new Date(d).toISOString().slice(0,10)}
function setView(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="workouts")renderWeek();if(v==="exercises")renderExercises();if(v==="timers")renderTimer()}
function completion(wid,day){return state.completions.find(c=>c.workoutId===wid&&dateKey(c.date)===dateKey(day))}
function renderWeek(){
 let ds=dates(); $("weekTitle").textContent=`${fmt(ds[0])} — ${fmt(ds[6])}`;
 $("weekList").innerHTML=ds.map((d,di)=>{
  let ws=state.workouts.filter(w=>w.day===di);
  let rows=ws.length?ws.map(w=>{
   let c=completion(w.id,d);
   return `<div class="workout"><div class="workout-row"><div class="grow"><b>${esc(w.name)}</b><div class="meta">${w.exerciseIds.length} упражн.</div></div><span class="status ${c?"done":""}">${c?"Выполнено":"Запланировано"}</span></div><div class="actions">${c?`<button class="secondary small" data-a="details" data-id="${c.id}">Деталі</button>`:`<button class="primary small" data-a="start" data-id="${w.id}" data-date="${d.toISOString()}">Выполнить</button>`}<button class="secondary small" data-a="editw" data-id="${w.id}">Изменить</button><button class="danger small" data-a="delw" data-id="${w.id}">Удалить</button></div></div>`;
  }).join(""):"<div class=\"empty\">Тренировок нет</div>";
  return `<div class="card"><div class="day">${DAYS[di]}</div><div class="date">${fmt(d)}</div>${rows}</div>`;
 }).join("");
}
function renderExercises(){
 let q=$("exerciseSearch").value.trim().toLowerCase();
 let a=state.exercises.filter(e=>(e.name+" "+e.description+" "+e.defaultLoad).toLowerCase().includes(q));
 $("exerciseList").innerHTML=a.length?a.map(e=>`<div class="card"><b>${esc(e.name)}</b><div class="meta">${esc(e.description||"")}</div><div class="meta">Вага / еспандер: ${esc(e.defaultLoad||"—")}</div><div class="actions"><button class="secondary small" data-a="edite" data-id="${e.id}">Изменить</button><button class="danger small" data-a="dele" data-id="${e.id}">Удалить</button></div></div>`).join(""):"<div class=\"empty\">Ничего не найдено.</div>";
}
function modal(title,body,ok){let r=$("modalRoot");r.innerHTML=`<div class="modal-backdrop" id="mb"><div class="modal"><div class="modal-head"><h2>${title}</h2><button id="mc">×</button></div>${body}<div class="modal-actions"><button class="secondary" id="cancel">Отмена</button><button class="primary" id="ok">Сохранить</button></div></div></div>`;let close=()=>r.innerHTML="";$("mc").onclick=close;$("cancel").onclick=close;$("mb").onclick=e=>{if(e.target.id==="mb")close()};$("ok").onclick=()=>{if(ok()!==false)close()}}
function workoutForm(w){let ids=[...(w?.exerciseIds||[])];let body=`<div class="field"><label>Название</label><input id="wn" class="input" value="${esc(w?.name||"")}"></div><div class="field"><label>День недели</label><select id="wd" class="select">${DAYS.map((x,i)=>`<option value="${i}" ${(w?.day??dayIndex(new Date()))===i?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Упражнения</label><div id="picker">${state.exercises.map(e=>`<label class="check"><input type="checkbox" value="${e.id}" ${ids.includes(e.id)?"checked":""}>${esc(e.name)}</label>`).join("")}</div></div><div class="field"><label>Параметры упражнения</label><div id="params"></div></div>`;modal(w?"Изменить тренировку":"Новая тренировка",body,()=>{let name=$("wn").value.trim();if(!name){toast("Введите название");return false}let items=ids.map(id=>({exerciseId:id,reps:$("r_"+id)?.value||"",load:$("l_"+id)?.value||""}));let obj={id:w?.id||uid("wo"),name,day:+$("wd").value,exerciseIds:ids,items};if(w)Object.assign(w,obj);else state.workouts.push(obj);save();renderWeek();toast("Сохранено")});let p=$("picker"),params=$("params");function refresh(){params.innerHTML=ids.map(id=>{let e=state.exercises.find(x=>x.id===id),it=(w?.items||[]).find(x=>x.exerciseId===id)||{};return `<div class="card" style="margin-bottom:8px"><b>${esc(e?.name)}</b><div class="wheel"><div><label>Повторы</label><input id="r_${id}" class="input" value="${esc(it.reps||"")}" inputmode="numeric"></div><div><label>Вага / еспандер</label><input id="l_${id}" class="input" value="${esc(it.load||e?.defaultLoad||"")}"></div></div></div>`}).join("")||"<div class='empty'>Выберите упражнения</div>"}p.onchange=e=>{let id=e.target.value;if(e.target.checked&&!ids.includes(id))ids.push(id);if(!e.target.checked)ids=ids.filter(x=>x!==id);refresh()};refresh()}
function exerciseForm(e){modal(e?"Изменить упражнение":"Новое упражнение",`<div class="field"><label>Название</label><input id="en" class="input" value="${esc(e?.name||"")}"></div><div class="field"><label>Описание / примечание</label><textarea id="ed" class="textarea">${esc(e?.description||"")}</textarea></div><div class="field"><label>Вага / еспандер по умолчанию</label><input id="el" class="input" value="${esc(e?.defaultLoad||"")}" placeholder="20 кг / червоний еспандер"></div>`,()=>{let name=$("en").value.trim();if(!name){toast("Введите название");return false}if(e)Object.assign(e,{name,description:$("ed").value.trim(),defaultLoad:$("el").value.trim()});else state.exercises.push({id:uid("ex"),name,description:$("ed").value.trim(),defaultLoad:$("el").value.trim()});save();renderExercises();toast("Сохранено")})}
function startWorkout(wid,iso){let w=state.workouts.find(x=>x.id===wid);if(!w)return;let c={id:uid("run"),workoutId:wid,date:new Date(iso).toISOString(),start:new Date().toISOString(),stages:{warmup:0,main:0,cooldown:0},items:JSON.parse(JSON.stringify(w.items||[])),note:""};openRun(c,w)}
function openRun(c,w){let start=0;let elapsed=0;let running=false;let last=0;let times=c.stages;function sec(){return Math.floor(elapsed/1000)}function hh(s){s=Math.max(0,Math.floor(s));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")}function render(){let total=times.warmup+times.main+times.cooldown;$("timerPanel").innerHTML=`<div class="card timer-card"><div class="timer-type">${esc(w.name)}</div><div class="stage-grid">${[["warmup","РОЗМИНКА"],["main","ОСНОВНАЯ"],["cooldown","ЗАМИНКА"]].map(x=>`<button class="${stage===x[0]?"active":""}" data-stage="${x[0]}">${x[1]}<br>${hh(times[x[0]])}</button>`).join("")}</div><div class="bigtime">${hh(times[stage]+sec())}</div><div class="controls"><button class="primary" id="runToggle">${running?"Пауза":"Старт"}</button><button class="secondary" id="finishStage">Завершить</button></div><div class="meta" style="margin-top:12px">Общее время: ${hh(total)}</div><div class="actions"><button class="secondary" id="finishWorkout">Завершить тренировку</button><button class="secondary" id="backTimers">К таймерам</button></div></div>`;document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>{if(running)pause();stage=b.dataset.stage;elapsed=0;render()});$("runToggle").onclick=()=>running?pause():resume();$("finishStage").onclick=finishStage;$("finishWorkout").onclick=finishWorkout;$("backTimers").onclick=()=>{timer=null;renderTimer()}}function resume(){running=true;start=Date.now();last=Date.now();tick()}function pause(){if(!running)return;elapsed+=Date.now()-start;running=false;clearTimeout(timer);render()}function tick(){if(!running)return;let now=Date.now();elapsed+=now-last;last=now;render();timer=setTimeout(tick,250)}function finishStage(){pause();times[stage]=Math.floor(elapsed/1000)+times[stage];elapsed=0;render()}function finishWorkout(){pause();times[stage]+=Math.floor(elapsed/1000);let total=times.warmup+times.main+times.cooldown;let note=prompt("Примечание:","")||"";c.stages=times;c.note=note;c.total=total;c.date=new Date().toISOString();state.completions.push(c);save();toast("Тренировка сохранена");timer=null;setView("workouts")}render()}
function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}function beep(kind){if(!sound)return;try{ensureAudio();let o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;let cfg=kind==="warning"?[880,.09]:kind==="cycle"?[660,.12]:[520,.24];o.frequency.value=cfg[0];o.type="sine";g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.16,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+cfg[1]);o.connect(g).connect(audio.destination);o.start(now);o.stop(now+cfg[1]+.02)}catch(e){}}
function renderTimer(){if(timerMode==="stopwatch")renderStopwatch();if(timerMode==="rest")renderRest();if(timerMode==="interval")renderInterval()}
function renderStopwatch(){if(timer)return;$("timerPanel").innerHTML=`<div class="card timer-card"><div class="timer-type">Секундомер этапа</div><div class="stage-grid">${[["warmup","РОЗМИНКА"],["main","ОСНОВНАЯ"],["cooldown","ЗАМИНКА"]].map(x=>`<button class="${stage===x[0]?"active":""}" data-s="${x[0]}">${x[1]}</button>`).join("")}</div><div class="bigtime">00:00:00</div><div class="controls"><button class="primary" id="swStart">Старт</button></div><div class="meta">Пауза не считается в фактическое время.</div></div>`;document.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>{stage=b.dataset.s;renderTimer()});$("swStart").onclick=()=>{let c={id:uid("run"),workoutId:null,date:new Date().toISOString(),start:new Date().toISOString(),stages:{warmup:0,main:0,cooldown:0},items:[],note:""};let dummy={name:stage==="warmup"?"Разминка":stage==="main"?"Основная часть":"Заминка"};openRun(c,dummy)}}
function wheelOptions(max){return Array.from({length:max+1},(_,i)=>`<option value="${i}">${String(i).padStart(2,"0")}</option>`).join("")}
function renderRest(){let r=timer?.kind==="rest"?timer:null;if(r){renderCountdown(r);return}$("timerPanel").innerHTML=`<div class="card timer-card"><div class="timer-type">ВІДПОЧИНОК</div><div class="wheel"><select id="rm">${wheelOptions(59)}</select><select id="rs">${wheelOptions(59)}</select></div><div class="bigtime">00:30</div><div class="controls"><button class="primary" id="restStart">Старт</button></div></div>`;let update=()=>$("timerPanel").querySelector(".bigtime").textContent=String(+$("rm").value).padStart(2,"0")+":"+String(+$("rs").value).padStart(2,"0");$("rm").value=0;$("rs").value=30;$("rm").onchange=update;$("rs").onchange=update;$("restStart").onclick=()=>{let dur=(+$('rm').value*60)+(+$('rs').value);if(!dur){toast("Выберите время");return}timer={kind:"rest",duration:dur*1000,remaining:dur*1000,paused:false,warningFired:false,endAt:Date.now()+dur*1000};renderCountdown(timer)}}
function renderCountdown(t){let sec=Math.max(0,Math.ceil((t.paused?t.remaining:t.endAt-Date.now())/1000));if(!t.paused&&!t.warningFired&&sec<=5&&sec>0){t.warningFired=true;beep("warning")}$("timerPanel").innerHTML=`<div class="card timer-card"><div class="timer-type">${t.kind==="rest"?"ВІДПОЧИНОК":t.phase}</div><div class="bigtime">${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}</div><div class="controls"><button class="primary" id="ct">${t.paused?"Продолжить":"Пауза"}</button><button class="secondary" id="cr">Сбросить</button></div></div>`;$("ct").onclick=()=>{if(t.paused){t.paused=false;t.endAt=Date.now()+t.remaining;renderCountdown(t)}else{t.remaining=Math.max(0,t.endAt-Date.now());t.paused=true;clearTimeout(timer);renderCountdown(t)}};$("cr").onclick=()=>{timer=null;clearTimeout(timer);renderRest()};if(!t.paused){if(sec<=0){beep("end");timer=null;alert(t.kind==="rest"?"Відпочинок завершено":"Период завершён");renderTimer();return}clearTimeout(timer);timer=setTimeout(()=>renderCountdown(t),250)}}
function renderInterval(){let t=timer?.kind==="interval"?timer:null;if(t){renderCountdown(t);return}$("timerPanel").innerHTML=`<div class="card"><div class="field"><label>Повторы</label><input id="ir" class="input" type="number" min="1" max="99" value="4"></div><div class="field"><label>Работа (сек)</label><input id="iw" class="input" type="number" min="1" value="50"></div><div class="field"><label>Отдых (сек)</label><input id="io" class="input" min="0" type="number" value="30"></div><button id="savePreset" class="secondary small">Сохранить пресет</button><button id="intervalStart" class="primary" style="margin-left:6px">Старт</button><div class="presets">${state.presets.map((p,i)=>`<div class="preset"><span>${esc(p.name)} · ${p.reps}×${p.work}/${p.rest}</span><span><button class="secondary small" data-p="${i}">Запустить</button><button class="danger small" data-del="${i}">×</button></span></div>`).join("")}</div></div>`;$("intervalStart").onclick=()=>startInterval(+$('ir').value,+$('iw').value,+$('io').value);$("savePreset").onclick=()=>{let name=prompt("Название пресета:","Кардио");if(!name)return;state.presets.push({name,reps:+$('ir').value,work:+$('iw').value,rest:+$('io').value});save();renderInterval()};document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{let p=state.presets[+b.dataset.p];startInterval(p.reps,p.work,p.rest)});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.presets.splice(+b.dataset.del,1);save();renderInterval()})}
function startInterval(reps,work,rest){timer={kind:"interval",reps,current:1,phase:"РАБОТА",work:work*1000,rest:rest*1000,remaining:work*1000,endAt:Date.now()+work*1000,warningFired:false,paused:false};handleInterval(timer)}
function intervalTick(){/* state is represented by timestamp; renderCountdown advances it */}

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll("[data-timer]").forEach(b=>b.onclick=()=>{timerMode=b.dataset.timer;document.querySelectorAll("[data-timer]").forEach(x=>x.classList.toggle("active",x===b));timer=null;renderTimer()});$("soundToggle").onclick=()=>{sound=!sound;$("soundToggle").textContent="Звук: "+(sound?"Вкл":"Вык")};$("prevWeek").onclick=()=>{weekOffset--;renderWeek()};$("nextWeek").onclick=()=>{weekOffset++;renderWeek()};$("addWorkout").onclick=()=>workoutForm();$("addExercise").onclick=()=>exerciseForm();$("exerciseSearch").oninput=renderExercises;$("installHint").onclick=()=>alert("Safari → Поделиться → На экран Домой");document.addEventListener("click",e=>{let b=e.target.closest("[data-a]");if(!b)return;let a=b.dataset.a,id=b.dataset.id;if(a==="editw")workoutForm(state.workouts.find(w=>w.id===id));if(a==="delw"&&confirm("Удалить тренировку?")){state.workouts=state.workouts.filter(w=>w.id!==id);save();renderWeek()}if(a==="edite")exerciseForm(state.exercises.find(x=>x.id===id));if(a==="dele"&&confirm("Удалить упражнение?")){state.exercises=state.exercises.filter(x=>x.id!==id);state.workouts.forEach(w=>{w.exerciseIds=w.exerciseIds.filter(x=>x!==id);w.items=(w.items||[]).filter(x=>x.exerciseId!==id)});save();renderExercises();renderWeek()}if(a==="start")startWorkout(id,b.dataset.date);if(a==="details"){let c=state.completions.find(x=>x.id===id);if(!c)return;let w=state.workouts.find(x=>x.id===c.workoutId);modal("Деталі",`<div class="card"><b>${esc(w?.name||"Тренировка")}</b><div class="meta">${fmt(c.date)}</div><div class="meta">Разминка: ${fmtSec(c.stages.warmup)} · Основная: ${fmtSec(c.stages.main)} · Заминка: ${fmtSec(c.stages.cooldown)} · Общее: ${fmtSec(c.total)}</div></div><div class="stack" style="margin-top:10px">${(c.items||[]).map(it=>{let x=state.exercises.find(e=>e.id===it.exerciseId);return `<div class="card"><b>${esc(x?.name||"")}</b><div class="meta">${esc(it.reps||"")} повторов · ${esc(it.load||"")}</div></div>`}).join("")}<div class="field"><label>Примечание</label><textarea id="dn" class="textarea">${esc(c.note||"")}</textarea></div>`,()=>{c.note=$("dn").value.trim();save();renderWeek();toast("Изменено")})}});
function fmtSec(s){s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
// Interval transition handling: replace generic countdown completion with explicit phase progression.
const originalRenderCountdown=renderCountdown;
// Generic function above is intentionally wrapped here by timer-loop interception below.
function handleInterval(t){let sec=Math.max(0,Math.ceil((t.paused?t.remaining:t.endAt-Date.now())/1000));if(!t.paused&&!t.warningFired&&sec<=5&&sec>0){t.warningFired=true;beep("warning")}if(sec<=0&&!t.paused){beep("end");if(t.phase==="РАБОТА"){if(t.current>=t.reps){beep("cycle");timer=null;alert("Интервалы завершены");renderInterval();return}if(t.rest>0){t.phase="ОТДЫХ";t.remaining=t.rest;t.endAt=Date.now()+t.rest;t.warningFired=false;beep("cycle")}else{t.current++;t.phase="РАБОТА";t.remaining=t.work;t.endAt=Date.now()+t.work;t.warningFired=false;beep("cycle")}}else{t.current++;t.phase="РАБОТА";t.remaining=t.work;t.endAt=Date.now()+t.work;t.warningFired=false;beep("cycle")}sec=Math.max(0,Math.ceil((t.endAt-Date.now())/1000))}$("timerPanel").innerHTML=`<div class="card timer-card"><div class="timer-type">${t.phase}</div><div class="interval-summary"><div class="metric"><b>${t.current} / ${t.reps}</b><span>Повтор</span></div><div class="metric"><b>${t.phase==="РАБОТА"?"РАБОТА":"ОТДЫХ"}</b><span>Фаза</span></div><div class="metric"><b>${fmtSec(sec)}</b><span>Осталось</span></div></div><div class="bigtime">${fmtSec(sec)}</div><div class="controls"><button class="primary" id="ct">${t.paused?"Продолжить":"Пауза"}</button><button class="secondary" id="cr">Сбросить</button></div></div>`;$("ct").onclick=()=>{if(t.paused){t.paused=false;t.endAt=Date.now()+t.remaining;renderTimer()}else{t.remaining=Math.max(0,t.endAt-Date.now());t.paused=true;clearTimeout(timer);renderTimer()}};$("cr").onclick=()=>{timer=null;clearTimeout(timer);renderInterval()};if(!t.paused){clearTimeout(timer);timer=setTimeout(()=>handleInterval(t),250)}}
// Rebind interval timer renderer to the timestamp-based state machine.
const oldTimerRender=renderTimer;renderTimer=()=>{if(timerMode==="interval"&&timer?.kind==="interval")handleInterval(timer);else oldTimerRender()};
window.addEventListener("pageshow",()=>{if(timer){if(timer.kind==="interval")handleInterval(timer);else renderCountdown(timer)}});window.addEventListener("visibilitychange",()=>{if(!document.hidden&&timer){if(timer.kind==="interval")handleInterval(timer);else renderCountdown(timer)}});
if("serviceWorker" in navigator&&location.protocol==="https:")addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));renderWeek();
})();
